target_dir: ../tests/data/segmentation
train_dirs:
    - train_1
    - train_2
val_dirs:
    - validation
test_dirs:
    - test
training: yes
task: segmentation # classification or segmentation is supported
model_name: deeplab_v3
backbone: mobilenetv2
loss: dice_loss
epochs: 2
batch_size: 2
optimizer: adam
augmentation: no
learning_rate: 0.01
width: 512
height: 256
input_dir: image
mask_dir: label
trained_model_path:
result_dir: test_segmentation_result
class_names:
    - a 
    - b 
    - c 
    - d 
    - e 
    - f 
    - g 
    - h 
    - i 
    - j 
    - k 
    - l 
    - m 
    - n 
    - o 
    - p 
    - q 
    - r 
    - s 
    - t 
    - u 
    - v
