FROM tensorflow/tensorflow:2.0.0-gpu-py3

MAINTAINER Hiroki Matsuzaki

RUN apt-get update \
    && apt-get install -y apt-utils \
    && apt-get install -y vim git locales sudo \
    libglib2.0-0 libsm6 libxrender1 libxext6

RUN pip install --upgrade pip

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

COPY Pipfile ./
COPY Pipfile.lock ./
RUN pip install pipenv
RUN pipenv install --system
RUN rm Pipfile.lock

# create user
{% for user in user_list %}
RUN groupadd {{user.name}} -g {{user.uid}}
RUN useradd -m {{user.name}} -u {{user.uid}} -g {{user.uid}}
RUN usermod -s /bin/bash {{user.name}}
RUN echo "{{user.name}}:{{password}}" | chpasswd
{% if user.sudo == "true" %}
RUN gpasswd -a {{user.name}} sudo
{% endif %}
{% endfor %}

# cleanup
RUN apt-get autoremove && apt-get clean

WORKDIR /home/