target_dir: data/classification/images
result_root_dir: result/classification/images
train_dirs: # you must set train dirs to test classification
    - train_1
test_dirs:
    - test
training: no
task: classification
model_name: xception
train_params: 
    backbone: 
    activation: softmax
    optimizer: adam
    loss:  # no need to set value. only categorical for classification
    loss_params: 
        alpha: 
        beta: 
        gamma: 
    batch_size: 8 
    learning_rate: 0.001
epochs: 2
augmentation:
width: 80
height: 80
trained_path: result/classification/images/classification_result
result_dir: test_classification_result
