target_dir: data/classification/images
result_root_dir: result/classification/images
training: yes
train_dirs:
    - train_1
    - train_2
    - train_3
    - train_4
    - train_5
val_dirs:
    - train_6
    - train_7
task: classification # classification or segmentation or detection

epochs: 2
width: 80
height: 80
trained_path:
result_dir: classification_result

train_params: 
    model_name: xception
    backbone: 
    activation: softmax
    optimizer: adam
    loss:
      functions:
        CategoricalCrossentropy:
    batch_size: 4
    learning_rate: 0.001
    augmentation:
    weights_info:
        classes: 
        weights: 
mlflow: True
experiment_name: test_experiment
run_name: classification
user_name: test_user
tracking_uri: './mlruns' # path to mlruns
version: 0.0.0