target_dir: data/classification/videos
result_root_dir: result/classification/videos
train_dirs:
    - train
val_dirs:
    - validation
test_dirs:
    - test
training: yes
task: classification # classification or segmentation or detection
input_data_type: video # image or video
model_name: xception
train_params: 
    backbone: 
    activation: softmax
    optimizer: adam
    loss:  # no need to set value. only categorical for classification
    loss_params: 
        alpha: 
        beta: 
        gamma: 
    batch_size: 2
    learning_rate: 0.001
epochs: 2
augmentation:
width: 80
height: 80
batch_period: 5
trained_model_path:
result_dir: classification_video_result
skip_frame: 5
class_names:
    - cat
    # - flower
    - dog
