target_dir: data/classification/images
result_root_dir: result/classification/images
training: yes
train_dirs:
    - train_1
    - train_2
    - train_3
    - train_4
    - train_5
val_dirs:
    - train_6
    - train_7
task: classification # classification or segmentation or detection
model_name: xception
epochs: 2
augmentation:
width: 80
height: 80
trained_path:
result_dir: classification_result
train_params: 
    backbone: 
    activation: softmax
    optimizer: adam
    loss:  # no need to set value. only categorical for classification
    loss_params: 
        alpha: 
        beta: 
        gamma: 
    batch_size: 8 
    learning_rate: 0.001
