target_dir: data/segmentation
result_root_dir: result/segmentation
train_dirs:
    - train_1
    - train_2
val_dirs:
    - validation
test_dirs:
    - test
training: yes
task: segmentation # classification or segmentation is supported

train_params: 
    model_name: deeplab_v3
    backbone: 
        - xception
        - mobilenetv2
    activation: softmax
    optimizer: 
        - adam
        - sgd
    loss:
        - name: Categorical Focal Loss
          functions:
            CategoricalFocalLoss:
        - name: Categorical Focal Dice Loss
          functions:
            CategoricalFocalLoss: 
                alpha: 
                    - 0.1
                    - 1.0
                    - 0.05
                gamma:  # focal
                    - 1.0
                    - 5.0
                    - 0.05
            DiceLoss:
                beta: 
                    - 0.1
                    - 1.0
                    - 0.05
                class_weights:
                    0: 1
                    1: 1
                    2: 2
                    3: 2
    scheduler:
        - name: Cyclical LR
          functions:
            CyclicalLR:
                cyc_freq: 
                    - 2
                    - 10
                    - 1
                lr_max: 
                    - 0.0005
                    - 0.001
                lr_min: 
                    - 0.0001
                    - 0.0005
        - name: Cosine Decay
          functions:
            CosineDecay: 
                lr_max: 
                    - 0.0005
                    - 0.001
                lr_min: 
                    - 0.0001
                    - 0.0005
    batch_size:
        - 2 # min
        - 8 # max
        - 2 # step
    learning_rate: 
        - 0.00001  # min(10^n)
        - 0.1  # max(10^n)
    weights_info:
        classes: # assign only when you use backbone weights
        weights: 
    augmentation:
        # - horizontal_flip
        # - zoom

epochs: 2
segmentation_val_step: 2
n_trials: 3
width: 512
height: 256
input_dir: image
label_dir: label
trained_path:
result_dir: segmentation_result_optuna
class_names:
    - background
    - hoge
    - fuga
    - piyo
train_colors:
    - 0
    - 5
    - 10
    - 15
    