target_dir: data/segmentation
result_root_dir: result/segmentation
test_dirs:
    - test
training: no
task: segmentation
model_name: deeplab_v3
backbone: mobilenetv2
loss: dice_loss
epochs: 2
batch_size: 2
optimizer: adam
augmentation: no
learning_rate: 0.01
width: 512
height: 256
input_dir: image
label_dir: label
trained_path: result/segmentation/segmentation_result
result_dir: test_segmentation_result
class_names:
    - background
    - hoge
    - fuga
    - piyo
train_colors:
    - 0
    - 5
    - 10
    - 15
