target_dir: data/segmentation
result_root_dir: result/segmentation
train_dirs:
    - train_1
    - train_2
val_dirs:
    - validation
test_dirs:
    - test
training: yes
task: segmentation # classification or segmentation is supported
model_name: deeplab_v3
backbone: mobilenetv2
loss: categorical_crossentropy_loss
epochs: 2
segmentation_val_step: 2
batch_size: 4
n_trials: 3
optimizer: adam
learning_rate: 0.001
width: 512
height: 256
input_dir: image
label_dir: label
trained_path:
result_dir: segmentation_result
class_names:
    - background
    - hoge
    - fuga
    - piyo
train_colors:
    - 0
    - 5
    - 10
    - 15
