target_dir: data/segmentation
result_root_dir: result/segmentation
test_dirs:
    - test
training: no
task: segmentation
model_name: deeplab_v3
train_params: 
    backbone: mobilenetv2
    activation: softmax
    optimizer: adam
    loss: dice_loss
    loss_params: 
        alpha: 0.45
        beta: 0.55
        gamma: 5.0
    batch_size: 8 
    learning_rate: 0.001
epochs: 2
augmentation: no
width: 512
height: 256
input_dir: image
label_dir: label
trained_path: result/segmentation/segmentation_result
result_dir: test_segmentation_result
class_names:
    - background
    - hoge
    - fuga
    - piyo
train_colors:
    - 0
    - 5
    - 10
    - 15
