target_dir: data/segmentation
result_root_dir: result/segmentation
train_dirs:
    - train_1
    - train_2
val_dirs:
    - validation
test_dirs:
    - test
training: yes
task: segmentation # classification or segmentation is supported
model_name: deeplab_v3
train_params: 
    backbone: 
        - mobilenetv2
        - xception
    activation: softmax
    optimizer: 
        - adam
        - sgd
    loss: 
        - categorical_focal_loss
        - categorical_focal_dice_loss
    loss_params: 
        alpha: 
            - 0.1
            - 1.0
            - 0.05
        beta: 
            - 0.1
            - 1.0
            - 0.05
        gamma:  # focal
            - 1.0
            - 5.0
            - 0.05
    batch_size: 
        - 2 # min
        - 8 # max
        - 2 # step
    learning_rate: 
        - 0.00001  # min(10^n)
        - 0.1  # max(10^n)
epochs: 2
segmentation_val_step: 2
n_trials: 3
augmentation:
    # - horizontal_flip
    # - zoom
width: 512
height: 256
input_dir: image
label_dir: label
trained_path:
result_dir: segmentation_result
class_names:
    - background
    - hoge
    - fuga
    - piyo
train_colors:
    - 0
    - 5
    - 10
    - 15
    