target_dir: data/segmentation
result_root_dir: result/segmentation
train_dirs:
    - train_1
    - train_2
val_dirs:
    - validation
test_dirs:
    - test
training: yes
task: segmentation # classification or segmentation is supported
model_name: deeplab_v3
train_params: 
    backbone: mobilenetv2
    activation: softmax
    optimizer: adam
    loss: categorical_focal_loss
    loss_params: 
        alpha: 0.45
        beta: 0.55
        gamma: 5.0
    batch_size: 8 
    learning_rate: 0.001
weights_info: 
    classes: # assign only when you use backbone weights
    weights: 
epochs: 2
augmentation:
  HorizontalFlip:
  RandomCrop: 
        height: 256
        width: 512
        p: 1
  OneOf-1:
      Blur:
      MotionBlur:
        p: 1  # percentage of function inside 'OneOf'
      p: 1  # percetage of 'OneOf'
segmentation_val_step: 2
n_trials: 3
width: 512
height: 256
input_dir: image
label_dir: label
trained_path:
result_dir: segmentation_result
class_names:
    - background
    - hoge
    - fuga
    - piyo
train_colors:
    - 0
    - 5
    - 10
    - 15
