name: integration test

on: [push]

jobs:
  godfarmer_job:
    runs-on: [self-hosted, cml, gpu]
    name: A job to test godfarmer
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Godfamer action step
        uses: ./ # Uses an action in the root directory

