name: train-my-model

on: [push]

jobs:
  train:
    runs-on: [self-hosted, cml, gpu]

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        run: |
          echo 'Hi from CML!' >> report.md
#         cml-send-comment report.md

# on: [push]

# jobs:
#   godfarmer_job:
#     runs-on: ubuntu-latest
#     name: A job to test godfarmer
#     steps:
#       # To use this repository's private action,
#       # you must check out the repository
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Godfamer action step
#         uses: ./ # Uses an action in the root directory
#         id: farmer
