name: integration-test

on: [push]

jobs:
  train:
    runs-on: [self-hosted, cml, gpu]

    steps:
      - uses: actions/checkout@v2

      - name: Godfarmer
        run: |
          apt-get update
          apt-get install -y libgl1-mesa-dev python3-dev
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root
          python setup.py install
          cd example
          Godfarmer

