name: train-my-model

on: [push]

jobs:
  train:
    runs-on: [self-hosted, cml, gpu]

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        uses: ./
        id: farmer
        #  run: |
        #    docker exec -it farmer_hiroki ls
